spring:
  profiles:
<<<<<<< HEAD
    active: xfor
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true

---
spring:
  profiles: xfor
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project3
    username: root
    password: 123456
---

=======
    active: cdy
>>>>>>> 167d0960ca32dc2d12d607a9ac0382d2514a4697
