spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?characterEncoding=utf-8
server:
  port: 8080
  servlet:
    context-path: /

pagehelper:
  auto-dialect: mysql
  reasonable: true
  support-methods-arguments: true

#logging:
#  file: cf.log
#  level:
#     com:
#      cskaoyan:
#        mapper: debug
#  path: log