pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true

Spring:
  datasource:
    username: root
    password: 951101zwDD
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall

server:
  port: 80
  servlet:
    context-path: /