pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true

Spring:
  datasource:
    username: root
    password: 951101zwDD
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8

  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

server:
  port: 80
  servlet:
    context-path: /

  tomcat:
    uri-encoding: UTF-8