Spring:
  datasource:
    username: root
    password: 951101zwDD
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true

server:
  port: 80
  servlet:
    context-path: /admin

myoss:
  bucket: project-mall
  endpoint: oss-cn-beijing.aliyuncs.com
  accesskey: LTAIxnp89MtwEeiY
  secret: jLXWqpMRiADW0deKzKn3kft8u1hfxq