spring:
  profiles:
<<<<<<< HEAD
    active: xfor

=======
    active: mtan
>>>>>>> 9fdf6fcbfef6990008000a79318e320b8bdd31c7
---
myoss:
   bucket: project-mall
   endpoint: oss-cn-beijing.aliyuncs.com
   accesskey: LTAIxnp89MtwEeiY
   secret: jLXWqpMRiADW0deKzKn3kft8u1hfxq
---



