spring:
  profiles:
    active: xfor

myoss:
  bucket: xfor
  end-point: oss-cn-shenzhen.aliyuncs.com
  access-key: LTAIO5qvCfMxUHqt
  secret: Tks0mrDZicbo5h9IndPWHNjG28h0v9
---
myoss:
   bucket: project-mall
   endpoint: oss-cn-beijing.aliyuncs.com
   accesskey: LTAIxnp89MtwEeiY
   secret: jLXWqpMRiADW0deKzKn3kft8u1hfxq
---



