spring:
  profiles:
    active: mzy
---
myoss:
   bucket: project-mall.oss-cn-beijing.aliyuncs.com
   endpoint: oss-cn-beijing.aliyuncs.com
   accesskey: LTAIxnp89MtwEeiY
   secret: jLXWqpMRiADW0deKzKn3kft8u1hfxq
---



