spring:
  profiles:
    active: xfor
---
spring:
  profiles: xfor
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project3
    username: root
    password: 123456
---

