Spring:
  datasource:
    username: root
    password: 951101zwDD
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8

server:
  port: 80